name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  pull-requests: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v7

      - name: Install Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Install dependencies
        run: pnpm install

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v2
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish-script: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Use OIDC for npm authentication instead of NPM_TOKEN
          NPM_TOKEN: "" # https://github.com/changesets/changesets/issues/1152#issuecomment-3190884868
          NPM_CONFIG_PROVENANCE: true

      - name: Update Node-Red flow-library
        if: steps.changesets.outputs.published == 'true'
        uses: Zehir/update-package-node-red-flow-library-action@v1.0.5
        with:
          package-name: "node-red-contrib-deconz"
